# Yml

build:
  publish: build
  command: npm run dev
  environment:
    ACCESS_TOKEN: ${env:MY_SECRET}" # process.env.MY_SECRET

# Reference environment variables
context:
  production:
    environment:
      ACCESS_TOKEN: ${env:MY_SECRET} # process.env.MY_SECRET
      TWILIO: ${env:TWILIO_TOKEN}    # process.env.TWILIO_TOKEN
  # Call async values a.k.a bring your own secret store
  deploy-preview:
    environment:
      ACCESS_TOKEN: ${file(asyncValue.js)} # value from asyncValue.js
      TWILIO: ${env:TWILIO_TOKEN} # process.env.TWILIO_TOKEN
      SHARED: ${sharedValue} # value from sharedValue key above
  # Fallback values if no env found
  branch-deploy:
    environment:
      ACCESS_TOKEN: ${env:MY_OTHER_SECRET, 'fallback value'}
      SHARED: ${sharedValue}

# Call async value with input params
advancedExample:
  ACCESS_TOKEN: ${file(asyncValue.js, 'dev', ${sharedValue})}"

sharedValue: shared value

otherValue: other value